In [69]:
import yfinance as yf
import numpy as np
import pandas as pd

from itertools import combinations as cb

In [22]:
ticks = ['ATVI', 'AMZN', 'AAPL', 'BA', 'KO', 'DIS', 'XOM', 'F', 'GE', 'GS',
       'INTC', 'MCD', 'MSFT', 'NVDA', 'PFE', 'SBUX', 'UNH', 'WMT', 'ELV',
       'GOOGL', 'TSLA', 'GM', 'META', 'AAL', 'BABA']      

'''Meta, TSLA, AAL, BABA 지우기 일단 (기간이 짧음)''' 
ticks = ['ATVI', 'AMZN', 'AAPL', 'BA', 'KO', 'DIS', 'XOM', 'F', 'GE', 'GS',
       'INTC', 'MCD', 'MSFT', 'NVDA', 'PFE', 'SBUX', 'UNH', 'WMT', 'ELV',
       'GOOGL', 'GM']      


In [21]:
raw_data = yf.download(ticks)['Adj Close'].dropna()
# for idx in raw_data.columns:
#     print(idx)
#     print(len(raw_data[idx].dropna()))

[*********************100%***********************]  21 of 21 completed


## Set Return

$$R_{i, t+\Delta t} = \frac{S_{i,(t+\Delta t)}-S_{i,t}}{S_{i,t}}$$

In [26]:
d_ret_df = raw_data.pct_change().dropna()
d_ret_df.head()

AAPL      AMZN      ATVI        BA       DIS       ELV  \
Date                                                                     
2010-11-19 -0.005511  0.003959 -0.003413 -0.015787 -0.015168  0.040661   
2010-11-22  0.021614  0.033794  0.009418  0.006919 -0.001621  0.023204   
2010-11-23 -0.014775 -0.012853 -0.016964 -0.006715 -0.022463 -0.024179   
2010-11-24  0.019661  0.053805  0.012942  0.028459  0.020764 -0.011278   
2010-11-26  0.000635 -0.000282  0.001704 -0.009326 -0.004611 -0.013135   

                   F        GE        GM     GOOGL  ...      INTC        KO  \
Date                                                ...                       
2010-11-19  0.009925  0.011222  0.002048 -0.009605  ...  0.005709  0.007519   
2010-11-22 -0.004914 -0.011714 -0.005254  0.000660  ...  0.005203 -0.000777   
2010-11-23 -0.030864 -0.016843 -0.024354 -0.013886  ... -0.007529 -0.010114   
2010-11-24  0.015923  0.011421  0.006917  0.020514  ...  0.014225  0.015561   
2010-11-26  0.009405 -0.008783  0.009558 -0.008353  ... -0.002337 -0.007739   

                 MCD      MSFT      NVDA       PFE      SBUX       UNH  \
Date                                                                     
2010-11-19  0.007846 -0.005805  0.032282 -0.001782  0.005886  0.010384   
2010-11-22 -0.001507  0.001557  0.000727 -0.010119  0.003576  0.012778   
2010-11-23 -0.006413 -0.023707 -0.023256 -0.003608 -0.015225 -0.011245   
2010-11-24  0.005949  0.009952  0.024554  0.007242  0.035526  0.003606   
2010-11-26 -0.011827 -0.004730 -0.012346 -0.011984 -0.010800 -0.008292   

                 WMT       XOM  
Date                            
2010-11-19  0.007595  0.003271  
2010-11-22 -0.000183 -0.004962  
2010-11-23 -0.013056 -0.017239  
2010-11-24  0.006335  0.013047  
2010-11-26 -0.004999 -0.009301  

[5 rows x 21 columns]

In [42]:
'''Standard Return df'''
df = (d_ret_df - d_ret_df.mean()) / d_ret_df.std()
df.head()

AAPL      AMZN      ATVI        BA       DIS       ELV  \
Date                                                                     
2010-11-19 -0.364172  0.140778 -0.215998 -0.708355 -0.953915  2.193407   
2010-11-22  1.134695  1.576485  0.435788  0.268957 -0.128275  1.229678   
2010-11-23 -0.876090 -0.668251 -0.904342 -0.317902 -1.398535 -1.386197   
2010-11-24  1.026787  2.539428  0.614812  1.196068  1.236044 -0.673966   
2010-11-26 -0.024546 -0.063329  0.043918 -0.430258 -0.310513 -0.776508   

                   F        GE        GM     GOOGL  ...      INTC        KO  \
Date                                                ...                       
2010-11-19  0.455946  0.543565  0.077499 -0.613417  ...  0.282641  0.638788   
2010-11-22 -0.247966 -0.585257 -0.258144 -0.006426  ...  0.255662 -0.105354   
2010-11-23 -1.478931 -0.837683 -1.136161 -0.866584  ... -0.423609 -0.942811   
2010-11-24  0.740465  0.553365  0.301350  1.167582  ...  0.736961  1.360226   
2010-11-26  0.431242 -0.440986  0.422728 -0.539402  ... -0.146615 -0.729803   

                 MCD      MSFT      NVDA       PFE      SBUX       UNH  \
Date                                                                     
2010-11-19  0.598646 -0.409860  1.091808 -0.175898  0.299346  0.579084   
2010-11-22 -0.173566  0.036237 -0.034698 -0.791043  0.162759  0.727928   
2010-11-23 -0.578651 -1.494648 -0.890882 -0.310624 -0.948940 -0.766006   
2010-11-24  0.442031  0.544930  0.815910  0.490003  2.051914  0.157580   
2010-11-26 -1.025654 -0.344719 -0.501406 -0.928609 -0.687294 -0.582350   

                 WMT       XOM  
Date                            
2010-11-19  0.565788  0.174012  
2010-11-22 -0.054913 -0.332963  
2010-11-23 -1.082205 -1.088937  
2010-11-24  0.465215  0.776014  
2010-11-26 -0.439212 -0.600172  

[5 rows x 21 columns]

In [54]:
df['AAPL'] @ df['AMZN'].T / len(df['AAPL'])

0.4851065589914136

In [60]:
np.zeros((len(df.columns), len(df.columns))).shape

(21, 21)

In [58]:
len(df)

3019

In [67]:
cor = pd.DataFrame(index=df.columns, columns=df.columns)
cor['AAPL'].loc['AAPL']

nan

In [75]:
from itertools import combinations as cb

cor = pd.DataFrame(index=df.columns, columns=df.columns)

for x in cb(df.columns, 2):

    checker = df[list(x)]
    rho = (checker.iloc[:,0] @ checker.iloc[:,1].T) / len(df)
    cor[x[0]].loc[x[1]] = rho
    cor[x[1]].loc[x[0]] = rho

cor = cor.fillna(1).astype(float)
cor

AAPL      AMZN      ATVI        BA       DIS       ELV         F  \
AAPL   1.000000  0.485107  0.357502  0.391291  0.416494  0.342955  0.369133   
AMZN   0.485107  1.000000  0.367641  0.305292  0.390904  0.260136  0.307168   
ATVI   0.357502  0.367641  1.000000  0.224182  0.228903  0.226043  0.173641   
BA     0.391291  0.305292  0.224182  1.000000  0.527559  0.372473  0.517607   
DIS    0.416494  0.390904  0.228903  0.527559  1.000000  0.366011  0.514658   
ELV    0.342955  0.260136  0.226043  0.372473  0.366011  1.000000  0.359959   
F      0.369133  0.307168  0.173641  0.517607  0.514658  0.359959  1.000000   
GE     0.337534  0.262383  0.181559  0.555636  0.481686  0.361329  0.520683   
GM     0.368689  0.296874  0.188824  0.536887  0.518173  0.371651  0.750759   
GOOGL  0.559301  0.596291  0.383158  0.411352  0.468860  0.360782  0.383484   
GS     0.443037  0.361210  0.260851  0.545397  0.572955  0.436213  0.569966   
INTC   0.494365  0.391531  0.338706  0.426464  0.440801  0.346001  0.386278   
KO     0.352176  0.258959  0.212811  0.433302  0.466121  0.393422  0.382529   
MCD    0.391211  0.295389  0.218953  0.437995  0.446765  0.408461  0.406408   
MSFT   0.596263  0.564775  0.419879  0.406599  0.481723  0.407890  0.392317   
NVDA   0.508787  0.469498  0.358302  0.367037  0.394922  0.310988  0.385184   
PFE    0.315340  0.254255  0.217579  0.304210  0.351965  0.429225  0.280611   
SBUX   0.443802  0.420158  0.279200  0.467305  0.529514  0.382205  0.458445   
UNH    0.407354  0.318336  0.259362  0.385857  0.402596  0.782588  0.375324   
WMT    0.302481  0.246671  0.213718  0.211994  0.298082  0.270746  0.226177   
XOM    0.323099  0.243071  0.200745  0.509227  0.485059  0.393792  0.475565   

             GE        GM     GOOGL  ...      INTC        KO       MCD  \
AAPL   0.337534  0.368689  0.559301  ...  0.494365  0.352176  0.391211   
AMZN   0.262383  0.296874  0.596291  ...  0.391531  0.258959  0.295389   
ATVI   0.181559  0.188824  0.383158  ...  0.338706  0.212811  0.218953   
BA     0.555636  0.536887  0.411352  ...  0.426464  0.433302  0.437995   
DIS    0.481686  0.518173  0.468860  ...  0.440801  0.466121  0.446765   
ELV    0.361329  0.371651  0.360782  ...  0.346001  0.393422  0.408461   
F      0.520683  0.750759  0.383484  ...  0.386278  0.382529  0.406408   
GE     1.000000  0.509959  0.352809  ...  0.379111  0.407565  0.393271   
GM     0.509959  1.000000  0.409926  ...  0.425402  0.364423  0.405491   
GOOGL  0.352809  0.409926  1.000000  ...  0.484689  0.379587  0.399892   
GS     0.558451  0.599112  0.476717  ...  0.479056  0.423947  0.444881   
INTC   0.379111  0.425402  0.484689  ...  1.000000  0.388799  0.369192   
KO     0.407565  0.364423  0.379587  ...  0.388799  1.000000  0.513468   
MCD    0.393271  0.405491  0.399892  ...  0.369192  0.513468  1.000000   
MSFT   0.358881  0.409508  0.658507  ...  0.595731  0.427067  0.459380   
NVDA   0.321969  0.388511  0.525008  ...  0.533821  0.263671  0.319889   
PFE    0.340097  0.288946  0.347913  ...  0.356180  0.429531  0.330622   
SBUX   0.410881  0.450396  0.493675  ...  0.395204  0.437685  0.570120   
UNH    0.370097  0.383230  0.417868  ...  0.390139  0.425798  0.426203   
WMT    0.206932  0.215696  0.290015  ...  0.310130  0.377071  0.323316   
XOM    0.529503  0.478752  0.364145  ...  0.408860  0.441285  0.386974   

           MSFT      NVDA       PFE      SBUX       UNH       WMT       XOM  
AAPL   0.596263  0.508787  0.315340  0.443802  0.407354  0.302481  0.323099  
AMZN   0.564775  0.469498  0.254255  0.420158  0.318336  0.246671  0.243071  
ATVI   0.419879  0.358302  0.217579  0.279200  0.259362  0.213718  0.200745  
BA     0.406599  0.367037  0.304210  0.467305  0.385857  0.211994  0.509227  
DIS    0.481723  0.394922  0.351965  0.529514  0.402596  0.298082  0.485059  
ELV    0.407890  0.310988  0.429225  0.382205  0.782588  0.270746  0.393792  
F      0.392317  0.385184  0.280611  0.458445  0.375324  0.226177  0.475565  
GE     0.358881  0.

In [158]:
eig = np.linalg.eig
eigen_arr = np.array([eig(cor)[0]])
cor_eig_values = eig(cor)[0]
cor_eig_vector = eig(cor)[1]

/var/folders/0k/zyr795gx3hl6x1nytrrntcnc0000gn/T/ipykernel_5903/3059282119.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  eigen_arr = np.array([eig(cor)[0], [eig(cor)[1]]])


In [169]:
eig(cor)[0].reshape(-1,1)

array([[9.02163182],
       [1.6697981 ],
       [1.28573767],
       [0.92394333],
       [0.78473154],
       [0.21119564],
       [0.24063184],
       [0.71977683],
       [0.67969619],
       [0.63074781],
       [0.30271694],
       [0.58457688],
       [0.36043979],
       [0.3790385 ],
       [0.39361892],
       [0.51431676],
       [0.50152217],
       [0.4221418 ],
       [0.43057672],
       [0.47439305],
       [0.46876768]])

In [180]:
eig(cor).shape

AttributeError: 'tuple' object has no attribute 'shape'

In [251]:
eig = np.linalg.eig
cor_eig_values = eig(cor)[0]
cor_eig_vector = eig(cor)[1]
eig_df = pd.Series(data=np.vsplit(cor_eig_vector, len(cor_eig_vector)))
eig_df.index = cor_eig_values
eig_df = eig_df.sort_index(ascending=False)
#np.c_[cor_eig_values, np.array_split(cor_eig_vector, len(cor_eig_vector))[0]]

In [257]:
def cor_recover (cor, n_components):

    eig = np.linalg.eig
    cor_eig_values = eig(cor)[0]
    cor_eig_vector = eig(cor)[1]
    eig_df = pd.Series(data=np.vsplit(cor_eig_vector, len(cor_eig_vector)))
    eig_df.index = cor_eig_values
    eig_df = eig_df.sort_index(ascending=False)
    #np.c_[cor_eig_values, np.array_split(cor_eig_vector, len(cor_eig_vector))[0]]

In [258]:
eig_df.index  eig_df.values 

(Float64Index([  9.021631824443718,  1.6697981037292795,  1.2857376666492593,
                0.9239433271990996,  0.7847315381499639,  0.7197768329967423,
                0.6796961894462632,  0.6307478123887181,  0.5845768842049066,
                0.5143167616301167,  0.5015221700489518, 0.47439305419200867,
                0.4687676786298342,  0.4305767203231047,  0.4221417982365253,
                0.3936189209555707, 0.37903850209469325,  0.3604397936069932,
                0.3027169386952911, 0.24063184133512056, 0.21119564104384664],
              dtype='float64'),
 array([array([[-0.22409572, -0.26204949, -0.06811197, -0.01869406, -0.04928969,
                 0.04507947,  0.0445532 , -0.07260669,  0.11725327, -0.16334678,
                 0.06302037, -0.07806605,  0.03575691, -0.02337711,  0.21471468,
                -0.09752316, -0.58633921,  0.10419574, -0.13782614,  0.13336361,
                 0.6041831 ]])                                                  ,
        array([

In [238]:
cor_eig_values.reshape(-1,1)

array([[9.02163182],
       [1.6697981 ],
       [1.28573767],
       [0.92394333],
       [0.78473154],
       [0.21119564],
       [0.24063184],
       [0.71977683],
       [0.67969619],
       [0.63074781],
       [0.30271694],
       [0.58457688],
       [0.36043979],
       [0.3790385 ],
       [0.39361892],
       [0.51431676],
       [0.50152217],
       [0.4221418 ],
       [0.43057672],
       [0.47439305],
       [0.46876768]])

In [246]:
a = pd.Series(data=np.vsplit(cor_eig_vector, len(cor_eig_vector)))
a.index = cor_eig_values
a

9.021632    [[-0.22409572341558007, -0.2620494852096157, -...
1.669798    [[-0.19545994918253953, -0.3621873890147888, -...
1.285738    [[-0.14678457102668294, -0.35180804354557993, ...
0.923943    [[-0.22979473060682504, 0.21404267557977427, -...
0.784732    [[-0.2407419452009223, 0.11492315984629804, -0...
0.211196    [[-0.2079776486892641, 0.08972564771296093, 0....
0.240632    [[-0.22782989776068738, 0.2665003331114012, -0...
0.719777    [[-0.21692925632656973, 0.2829104731956634, -0...
0.679696    [[-0.2312016573098458, 0.2571310899426949, -0....
0.630748    [[-0.23840098816230382, -0.27628645434709154, ...
0.302717    [[-0.25329064890074604, 0.15992817288211764, -...
0.584577    [[-0.22773782754415878, -0.152764077199749, -0...
0.360440    [[-0.21276682426980165, 0.12188001214696575, 0...
0.379039    [[-0.21824787293874295, 0.07962726122756857, 0...
0.393619    [[-0.2522119426462242, -0.2940962882829722, -0...
0.514317    [[-0.21151475150352195, -0.27693309993716747, ...
0.501522

In [223]:
np.array_split(cor_eig_vector, len(cor_eig_vector))

[array([[-0.22409572, -0.26204949, -0.06811197, -0.01869406, -0.04928969,
          0.04507947,  0.0445532 , -0.07260669,  0.11725327, -0.16334678,
          0.06302037, -0.07806605,  0.03575691, -0.02337711,  0.21471468,
         -0.09752316, -0.58633921,  0.10419574, -0.13782614,  0.13336361,
          0.6041831 ]]),
 array([[-0.19545995, -0.36218739, -0.15157956, -0.01663213, -0.18293873,
          0.01609631,  0.06370385,  0.04866639,  0.16311829,  0.46177122,
          0.03452526, -0.23770634,  0.27100724, -0.31189666,  0.39100112,
          0.10115437, -0.0307423 , -0.08844784,  0.13097885, -0.09327486,
         -0.31813772]]),
 array([[-0.14678457, -0.35180804, -0.00843351, -0.09585906,  0.34047468,
         -0.00146052, -0.01125659,  0.49856287, -0.65799499,  0.09905181,
          0.03442277,  0.15075393, -0.03795363, -0.02487712,  0.00937006,
          0.0298374 ,  0.03005835, -0.02092855, -0.05365403, -0.02881947,
          0.077717  ]]),
 array([[-0.22979473,  0.21404268, -0

In [201]:
np.array(eig(cor)[1][x] for x in range(eig(cor)[1].shape[0])])

array([[[-2.24095723e-01, -2.62049485e-01, -6.81119729e-02,
         -1.86940564e-02, -4.92896891e-02,  4.50794684e-02,
          4.45531989e-02, -7.26066864e-02,  1.17253273e-01,
         -1.63346777e-01,  6.30203709e-02, -7.80660452e-02,
          3.57569078e-02, -2.33771083e-02,  2.14714683e-01,
         -9.75231561e-02, -5.86339207e-01,  1.04195738e-01,
         -1.37826137e-01,  1.33363613e-01,  6.04183101e-01]],

       [[-1.95459949e-01, -3.62187389e-01, -1.51579556e-01,
         -1.66321260e-02, -1.82938730e-01,  1.60963052e-02,
          6.37038529e-02,  4.86663864e-02,  1.63118288e-01,
          4.61771224e-01,  3.45252589e-02, -2.37706335e-01,
          2.71007239e-01, -3.11896660e-01,  3.91001124e-01,
          1.01154371e-01, -3.07423034e-02, -8.84478360e-02,
          1.30978849e-01, -9.32748617e-02, -3.18137720e-01]],

       [[-1.46784571e-01, -3.51808044e-01, -8.43351432e-03,
         -9.58590633e-02,  3.40474678e-01, -1.46051733e-03,
         -1.12565860e-02,  4.98562

In [193]:
eig(cor)[1]

array([[-2.24095723e-01, -2.62049485e-01, -6.81119729e-02,
        -1.86940564e-02, -4.92896891e-02,  4.50794684e-02,
         4.45531989e-02, -7.26066864e-02,  1.17253273e-01,
        -1.63346777e-01,  6.30203709e-02, -7.80660452e-02,
         3.57569078e-02, -2.33771083e-02,  2.14714683e-01,
        -9.75231561e-02, -5.86339207e-01,  1.04195738e-01,
        -1.37826137e-01,  1.33363613e-01,  6.04183101e-01],
       [-1.95459949e-01, -3.62187389e-01, -1.51579556e-01,
        -1.66321260e-02, -1.82938730e-01,  1.60963052e-02,
         6.37038529e-02,  4.86663864e-02,  1.63118288e-01,
         4.61771224e-01,  3.45252589e-02, -2.37706335e-01,
         2.71007239e-01, -3.11896660e-01,  3.91001124e-01,
         1.01154371e-01, -3.07423034e-02, -8.84478360e-02,
         1.30978849e-01, -9.32748617e-02, -3.18137720e-01],
       [-1.46784571e-01, -3.51808044e-01, -8.43351432e-03,
        -9.58590633e-02,  3.40474678e-01, -1.46051733e-03,
        -1.12565860e-02,  4.98562868e-01, -6.57994994e

In [186]:
np.array([eig(cor)[1][x] for x in range(eig(cor)[1].shape[0])])

array([[-2.24095723e-01, -2.62049485e-01, -6.81119729e-02,
        -1.86940564e-02, -4.92896891e-02,  4.50794684e-02,
         4.45531989e-02, -7.26066864e-02,  1.17253273e-01,
        -1.63346777e-01,  6.30203709e-02, -7.80660452e-02,
         3.57569078e-02, -2.33771083e-02,  2.14714683e-01,
        -9.75231561e-02, -5.86339207e-01,  1.04195738e-01,
        -1.37826137e-01,  1.33363613e-01,  6.04183101e-01],
       [-1.95459949e-01, -3.62187389e-01, -1.51579556e-01,
        -1.66321260e-02, -1.82938730e-01,  1.60963052e-02,
         6.37038529e-02,  4.86663864e-02,  1.63118288e-01,
         4.61771224e-01,  3.45252589e-02, -2.37706335e-01,
         2.71007239e-01, -3.11896660e-01,  3.91001124e-01,
         1.01154371e-01, -3.07423034e-02, -8.84478360e-02,
         1.30978849e-01, -9.32748617e-02, -3.18137720e-01],
       [-1.46784571e-01, -3.51808044e-01, -8.43351432e-03,
        -9.58590633e-02,  3.40474678e-01, -1.46051733e-03,
        -1.12565860e-02,  4.98562868e-01, -6.57994994e

In [167]:
eig(cor)[1][0]

array([-0.22409572, -0.26204949, -0.06811197, -0.01869406, -0.04928969,
        0.04507947,  0.0445532 , -0.07260669,  0.11725327, -0.16334678,
        0.06302037, -0.07806605,  0.03575691, -0.02337711,  0.21471468,
       -0.09752316, -0.58633921,  0.10419574, -0.13782614,  0.13336361,
        0.6041831 ])

In [151]:
eig = np.linalg.eig
cor_eig_values = eig(cor)[0]
cor_eig_vector = eig(cor)[1]
eigen_dict = {x:y for x, y in zip(cor_eig_values, cor_eig_vector)}
eigen_dict = dict(sorted(eigen_dict.items(), key=lambda item: item[0])[::-1]) #순서 정렬

In [156]:
list(eigen_dict.keys())[:10], list(eigen_dict.values())[:10]

([9.021631824443718,
  1.6697981037292795,
  1.2857376666492593,
  0.9239433271990996,
  0.7847315381499639,
  0.7197768329967423,
  0.6796961894462632,
  0.6307478123887181,
  0.5845768842049066,
  0.5143167616301167],
 [array([-0.22409572, -0.26204949, -0.06811197, -0.01869406, -0.04928969,
          0.04507947,  0.0445532 , -0.07260669,  0.11725327, -0.16334678,
          0.06302037, -0.07806605,  0.03575691, -0.02337711,  0.21471468,
         -0.09752316, -0.58633921,  0.10419574, -0.13782614,  0.13336361,
          0.6041831 ]),
  array([-0.19545995, -0.36218739, -0.15157956, -0.01663213, -0.18293873,
          0.01609631,  0.06370385,  0.04866639,  0.16311829,  0.46177122,
          0.03452526, -0.23770634,  0.27100724, -0.31189666,  0.39100112,
          0.10115437, -0.0307423 , -0.08844784,  0.13097885, -0.09327486,
         -0.31813772]),
  array([-0.14678457, -0.35180804, -0.00843351, -0.09585906,  0.34047468,
         -0.00146052, -0.01125659,  0.49856287, -0.65799499,  0.09

d_ret_df

In [29]:
from sklearn.decomposition import PCA

num_components = 10

pca = PCA(n_components=num_components)
pca.fit(d_ret_df)

PCA(n_components=10)